# Generated by Django 3.2 on 2023-04-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(
                blank=True, max_length=50, verbose_name='Код подтверждения'
            ),
        ),
    ]
