# Generated by Django 3.2 on 2023-04-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230421_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(null=True, through='reviews.TitleGenre', to='reviews.Genre'),
        ),
    ]
